//You are given two strings s and t.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Return the letter that was added to t.

//eg1: s= "abcd" t="adbce"   
//output : "e"
class Solution
{
  public char findThediff(String s, String t)
  {
    HashMap<Character,Integer> count = new HashMap<>();
    for(char c:s.toCharArray())
    {
      count.put(c,count.getOrDefault(c,0)+1);
    }
    for(char c:t.toCharArray())
    {
      
        if(!count.containsKey(c) || count.get(c) == 0)
        {
          return c;
        }
        count.put(c,count.get(c)-1);
    }
    char dummy = ' ';
    return dummy;
  }
}
//Time : O(N+M)
